spring.application.name=auraminds-app
app.access.code-hash=${ACCESS_CODE_HASH:9a7ee9ac01d74171d10a12e586d6829e00078bd8275637704f35054e4b16cf8d}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.open-in-view=false

spring.jackson.time-zone=UTC

server.port=${PORT:8080}

logging.level.root=INFO
logging.level.org.springframework.web=INFO